### ISSUE TITLE
VRT plugin API

### ISSUE THREAD

**Issue by billiemead** [bleech/visual-regression-tests#61]
Is the API necessary for the plugin to work? Or is it for licensing etc.?

I spent some more time today still trying to get VRT to work, and it starts up and runs the first test... but then it seems like it never finishes, as the first test is never completed.

I wasn't sure if the API endpoints needed to be working in order for the first test to run, and the link https://bleech-vrts-app.blee.ch/api/v1/ is still broken and doesn't resolve anywhere.

**Comment by steffenbew** [comment]
Hi @billiemead, I'm sorry you're having troubles with getting the plugin to work.

The API is essential for the plugin to work, as the screenshots and comparisons are done by our external service. This service then notifies your plugin installation about the test results (via API push or polling from the plugin). Please note that your website must be publicly accessible so that our service can take screenshots.

The URL you referenced serves as the API's root, but it's not an endpoint to interact with. That's why not getting a result on that base URL doesn't mean the API is broken. The API is fully operational as of now.

Where did you install the plugin and which [installation method](https://github.com/bleech/visual-regression-tests?tab=readme-ov-file#installation) did you use? If you provide us with the website URL, we'll be able to investigate the requests from your installation to our service and may advise you towards a resolution.

**Comment by billiemead** [comment]
@steffenbew Thank you for the help! I am currently working in a local dev environment, but I will push it to a live site in the next few days and absolutely will share the link. I really appreciate the help and am looking forward to getting it working, as I already have approval from the company I work [for](https://www.agencynetworkmjh.com/) the get a paid subscription for a solution that works for us and our regression testing needs.

**Comment by steffenbew** [comment]
@billiemead Ah alright, then running it locally is the culprit! Try it once the website is live and I'm confident it will work fine. If it doesn't, please feel free to get back to me again!
